name: Build and publish Elastic Agent
on:
  push:
    branches:
      - main
    paths:
      - 'internal/**'
      - 'pkg/**'
      - 'tools/**'
      - 'testing/**'
      - 'wrapper/**'
      - 'dev-tools/**'
      - '**/*.go'
      - '!**/*_test.go'
      - 'go.mod'
      - 'go.sum'
      - '.go-version'
      - 'Dockerfile'
      - 'control_v1.proto'
      - 'control_v2.proto'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.2'
      - name: Build binary and generate build hash
        env:
          DEV: "false"
          SNAPSHOT: "false"
        run: |
          go install github.com/magefile/mage@latest
          mage build
          git rev-parse HEAD | cut -c 1-6 > .build_hash.txt
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          context: .
          file: Dockerfile
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha }}
